site_name: "NCOR"
repo_url: https://github.com/johnbeve/NCOR-Test/
site_description: NCOR Homepage
site_author: John Beverley
edit_uri: '?query=root/NCOR-Test/docs/'

theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - About: index.md
  - NCOR Labs: 
    - Ontology 101 WG: ontology-101-wg.md
    - Common Core Ontologies WG: cco-wg.md
    - Semantic Mappings WG: semantic-map-wg.md
    - Industrial Ontologies WG: iof-wg.md
  - Affiliates: 
    - People: people.md
    - Organizations: organizations.md
  - Publications: publications.md
  - Training: training.md
  - Events: events.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
    - icon: fontawesome/brands/github
    - icon: fontawesome/brands/slack

extra_css: [extra.css]