site_name: "NCOR"
repo_url: https://github.com/johnbeve/NCOR-Test/
site_description: NCOR Homepage
site_author: John Beverley
edit_uri: '?query=root/NCOR-Test/docs/'

extra_css: 
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/ncor-logo.png
  palette:
    primary: black
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - About: index.md
  - NCOR Labs: 
    - Ontology 101 WG: ontology-101-wg.md
    - Common Core Ontologies WG: cco-wg.md
    - Semantic Mappings WG: semantic-map-wg.md
    - Industrial Ontologies WG: iof-wg.md
  - Affiliates: 
    - People: people.md
    - Organizations: organizations.md
  - Training: 
    - NCOR Pathways: training.md
    - Foundations: foundations.md
    - Associate: associate.md
    - Specialist: specialists.md
    - Bootcamps: bootcamps.md
  - Events: events.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
    - icon: fontawesome/brands/github
    - icon: fontawesome/brands/slack

markdown_extensions:
    - attr_list